############################################################
# | AddLight by hexosse                                  | #
############################################################


# *---------------- Plugin configuration --------------------*
plugin:
  # Enable metrics
  useMetrics : true
  # Enable updater
  useUpdater : true
  # Download update
  downloadUpdate: true


############################################################