name: ${project.name}
version: ${project.version}
description: ${project.description}
main: com.github.hexosse.addlight.AddLight

author: hexosse
website: www.github.hexosse

depend: [LightAPI]
softdepend: []

commands:
  AddLight:
    aliases: [al]
    description: Add invisible light source to item when clicked with glowstone dust.
    usage: |
           /AddLight help : Display AddLight help
           /AddLight [enable|on] : Enable light creation
           /AddLight [disable|off] : Disable light creation
           /AddLight <number> : Define light intensity (1-15)

permissions:
  AddLight.*:
    description: Gives access to all AddLight permissions
    default: op
    children:
        AddLight.admin: true
AddLight.admin:
    description: Allows creation of light
    default: op
