name: ${project.name}
version: ${project.version}
description: ${project.description}
main: com.github.hexosse.addlight.AddLight

author: hexosse
website: www.github.hexosse

depend: [LightAPI]
softdepend: [WorldEdit]

commands:
  AddLight:
    aliases: [al]
    description: Add invisible light source to item when clicked with glowstone dust.
    usage: |
           /AddLight help : Display AddLight help
           /AddLight [enable|on] : Enable light creation
           /AddLight [disable|off] : Disable light creation
           /AddLight <number> : Define light intensity (1-15)
           /AddLight ConnectedBlocks : Create lights to all connected blocks (be very carreful)

permissions:
  AddLight.admin: {description: Allows creation of light to admin users, default: false}
  AddLight.user: {description: Allows creation of light to any users, default: false}
  AddLight.use: {description: Allows a user to use this plugin, default: false}
  AddLight.worldedit: {description: AddLight can apply to a WorldEditSelection, default: false}
  AddLight.connected: {description: AddLight can apply to any connected blocks, default: false}
  AddLight.intensity: {description: user can change the light intensity, default: false}
  AddLight.*:
    default: op
    children:
        AddLight.admin: true
  AddLight.admin:
    children:
        AddLight.use: true
        AddLight.worldedit: true
        AddLight.connected: true
        AddLight.intensity: true
  AddLight.user:
    children:
        AddLight.use: true
